services:
  moderacion:
    build: ./app/moderacion
    ports:
      - "5001:5001"
    restart: unless-stopped

  api:
    build: ./app/api
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MODERACION_URL=http://moderacion:5001
    depends_on:
      - moderacion
    restart: unless-stopped
